object Versions {
    const val kotlin_version = "1.3.72"
    const val dagger_version = "2.27"
    const val navigation_version = "2.3.5"
    const val androidx_core_version = "1.3.2"
    const val androidx_appcompat_version = "1.2.0"
    const val country_code_picker_version = "2.5.1"
    const val circle_image_view_version = "3.1.0"
    const val pix_image_picker_version = "1.5.6"
    const val badged_table_layout_version = "v1.2"
    const val material_search_bar = "0.8.5"
    const val material_version = "1.3.0"
    const val constraint_layout_version = "2.0.4"
    const val shape_of_view = "1.4.7"
    const val legacy_support_version = "1.0.0"
    const val firebase_platform_version = "27.1.0"
    const val firebase_core_version = "16.0.9"
    const val compressor_version = "3.0.1"
    const val coroutines_version = "1.3.0"
    const val glide_version = "4.12.0"
}